# Generated by Django 2.2.24 on 2021-06-04 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoCurso', models.CharField(max_length=20)),
                ('NombreCurso', models.CharField(max_length=50)),
                ('FechaInicio', models.DateField()),
                ('FechaFin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=80)),
                ('Apellidos', models.CharField(max_length=80)),
                ('FechaNacimento', models.DateField()),
                ('Genero', models.CharField(choices=[(0, 'Masculino'), (1, 'Femenino'), (2, 'NoDefinido')], max_length=1)),
                ('Cursos', models.ManyToManyField(to='api.Curso', verbose_name='Cursos')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StringDireccion', models.CharField(max_length=80)),
                ('TipoDireccion', models.CharField(choices=[(0, 'Domicilio'), (1, 'Laboral'), (2, 'Temporal')], max_length=1)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Estudiante', verbose_name='Estudiante')),
            ],
        ),
    ]
